### PR TITLE
Remove skip on win

### PR DESCRIPTION
**Pull request by mrava87**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mrava87** [comment]
@conda-forge-admin, please rerender

**Comment by mrava87** [comment]
@jan-janssen I was asked to add windows to the condo-forge distributions. 

Tests are now working for linux+mac+windows on azure pipelines. I have updated the recipe but I need someone to accept this PR https://github.com/conda-forge/scikit-fmm-feedstock/pull/1 first, can you do that?

**Comment by jan-janssen** [comment]
Sure, if you want to I can also add you as a maintainer

**Comment by mrava87** [comment]
@conda-forge-admin, please rerender

**Comment by mrava87** [comment]
@conda-forge-admin, please rerender

**Comment by mrava87** [comment]
@jan-janssen mmh do you understand why the win build still fails on ``scikit-fmm``, do I need to wait some time for that to be available after you merged it?

**Comment by jan-janssen** [comment]
Hi @mrava87 I decreased the build number and now it is working. The reason is that Anaconda is using a content delivery network so even though a package is listed on the website it might still take a few minutes (maximum an hour) for the package to be available worldwide. That is why the AppVeyor test worked and the Azure test failed. From my perspective we can merge it now.

**Comment by mrava87** [comment]
Right I see :) thanks a lot, this is good to go :)

**Pull request merged**
