### PR TITLE
Increase version to v1.5.0

### PR DESCRIPTION
**Pull request by mrava87**
Hi @jan-janssen, 
we just released v1.5.0. I tried to update this recipe, as its the first time I do it, would you mind taking a look :)

Also I modified the short description of the package in the same meta.yaml file to match that on PyPi, hope this is ok?

Checklist
* [X] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
Hi @mrava87, 

Usually conda-forge automates this process for us - the automatic pull request is: 
https://github.com/conda-forge/pylops-feedstock/pull/3

To do the steps manually, it is important to also update the sha256 hash, as that is what is used to validate the package during the build process: 
https://github.com/conda-forge/pylops-feedstock/pull/2/commits/059bc660cfd715bec007f5d89ddfec77ffe83e86 

Afterwards just calling the rerender command helps us to update the conda-forge related part to the latest version: 
https://github.com/conda-forge/pylops-feedstock/pull/2#issuecomment-507037101 

After these steps the Python 3 tests work fine, but the Python 2.7 tests fail with: 
```
    except ModuleNotFoundError:
NameError: name 'ModuleNotFoundError' is not defined
```
This can be solved as explained in: 
https://stackoverflow.com/questions/52580105/exception-similar-to-modulenotfounderror-in-python-2-7

Now we have two options, either we patch the conda version using a .patch file, or you fix it in the main repository. We could also drop Python 2.7 support but I do not think that is necessary at this point.

**Comment by mrava87** [comment]
> Hi @mrava87,
> 
> Usually conda-forge automates this process for us - the automatic pull request is:
> #3

Sorry, I didn't realise that conda-forge does automatically this for us, I was too fast :( so next time I have a new release on pip I should just wait for conda-forge to make a PR?

> 
> To do the steps manually, it is important to also update the sha256 hash, as that is what is used to validate the package during the build process:
> [059bc66](https://github.com/conda-forge/pylops-feedstock/commit/059bc660cfd715bec007f5d89ddfec77ffe83e86)
> 
> Afterwards just calling the rerender command helps us to update the conda-forge related part to the latest version:
> [#2 (comment)](https://github.com/conda-forge/pylops-feedstock/pull/2#issuecomment-507037101)

I didn't realise the sha256 hash was per release not per project, I just found out how to get it from PyPI, sorry about that and thanks a lot for changing it. Now I know for next time :)

> 
> After these steps the Python 3 tests work fine, but the Python 2.7 tests fail with:
> 
> ```
>     except ModuleNotFoundError:
> NameError: name 'ModuleNotFoundError' is not defined
> ```
> 
> This can be solved as explained in:
> https://stackoverflow.com/questions/52580105/exception-similar-to-modulenotfounderror-in-python-2-7
> 

> Now we have two options, either we patch the conda version using a .patch file, or you fix it in the main repository. We could also drop Python 2.7 support but I do not think that is necessary at this point.

I see where this happens, this is something new in the code. My suggestion would be to drop Python2 directly if you don't mind. I didn't realise we released the previous version also in Python2.7, my bad, but Python2 support is definitely something not in the plan for PyLops, and it would be good to avoid any misunderstanding from the user side. While the import that we do while building conda-forge works (or at least used to...) I have never tried to run the tests in Python2 and would not be surprised if they may fail. What do you think?

**Comment by mrava87** [comment]
I thought ``skip: True  # [win or py2k]`` will skip all Python2 but they seem to be still there. Any idea how to do that?

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
> > Hi @mrava87,
> > Usually conda-forge automates this process for us - the automatic pull request is:
> > #3
> 
> Sorry, I didn't realise that conda-forge does automatically this for us, I was too fast :( so next time I have a new release on pip I should just wait for conda-forge to make a PR?

Yes, usually I just wait for conda-forge to create the PR and then merge it. 

> I thought `skip: True # [win or py2k]` will skip all Python2 but they seem to be still there. However it builds. Any idea why?

This can be done by: 
`conda-forge-admin, please rerender`

So I guess now we can merge it.

**Comment by mrava87** [comment]
Great, thanks a lot!
Was good to go through the process once, next time will be easier :)

**Pull request merged**
